# Generated by Django 3.1.4 on 2020-12-21 21:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('modo', models.CharField(max_length=100)),
                ('foto', models.CharField(max_length=100)),
                ('verificacion', models.IntegerField()),
                ('email_encriptado', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategoria', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('titulo', models.CharField(max_length=200)),
                ('titular', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('multimedia', models.CharField(max_length=100)),
                ('detalles', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('portada', models.CharField(max_length=100)),
                ('vistas', models.IntegerField()),
                ('ventas', models.IntegerField()),
                ('vistas_gratis', models.IntegerField()),
                ('ventas_gratis', models.IntegerField()),
                ('ofertado_por_categoria', models.IntegerField()),
                ('ofertado_por_sub_categoria', models.IntegerField()),
                ('oferta', models.IntegerField()),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descuento_oferta', models.IntegerField()),
                ('img_oferta', models.CharField(max_length=100)),
                ('fin_oferta', models.DateTimeField()),
                ('nuevo', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('entrega', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fecha', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.categoria')),
                ('subcategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.subcategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Deseo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('envio', models.IntegerField()),
                ('metodo', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=300)),
                ('pais', models.CharField(max_length=100)),
                ('fecha', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.FloatField()),
                ('comentario', models.CharField(max_length=200)),
                ('fecha', models.DateTimeField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.usuario')),
            ],
        ),
    ]
