# Generated by Django 3.1.4 on 2020-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_auto_20201222_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='ruta',
            field=models.ImageField(upload_to='productos'),
        ),
    ]
