# Generated by Django 3.1.4 on 2020-12-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0003_auto_20201226_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='img_oferta',
            field=models.ImageField(upload_to='img_oferta_producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='portada',
            field=models.ImageField(upload_to='portada_producto'),
        ),
    ]
