# Generated by Django 3.1.4 on 2020-12-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0004_auto_20201226_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto',
            field=models.ImageField(upload_to='usuarios'),
        ),
    ]
