# Generated by Django 3.1.4 on 2021-01-13 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0007_auto_20201231_0124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='categoria',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='categoria',
            old_name='ruta',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='comentario',
            new_name='texto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='titular',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descuento_oferta',
            new_name='stock',
        ),
        migrations.RenameField(
            model_name='subcategoria',
            old_name='ruta',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='foto',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='categoria',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='envio',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='metodo',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='compra',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='entrega',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='fin_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='img_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='multimedia',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='nuevo',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ofertado_por_categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ofertado_por_sub_categoria',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='portada',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio_oferta',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ventas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='ventas_gratis',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vistas',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='vistas_gratis',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='subcategoria',
            name='subcategoria',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email_encriptado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='modo',
        ),
        migrations.AddField(
            model_name='categoria',
            name='imagen',
            field=models.ImageField(default=1, upload_to='categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='compra',
            name='costo_envio',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='gratis',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='imagen',
            field=models.ImageField(default=1, upload_to='categorias'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcategoria',
            name='oferta',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='peso',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='verificacion',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.ImageField(upload_to='productos')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacion.producto')),
            ],
        ),
    ]
