# Generated by Django 3.1.4 on 2021-01-13 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0008_auto_20210113_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ruta',
        ),
    ]
