# Generated by Django 3.1.5 on 2021-01-15 05:09

import aplicacion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0011_auto_20210115_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='aplicacion.producto', validators=[aplicacion.models.file_size]),
        ),
    ]
