# Generated by Django 3.1.5 on 2021-01-15 05:11

import aplicacion.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0012_auto_20210115_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='aplicacion.producto'),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='ruta',
            field=models.ImageField(upload_to='productos', validators=[aplicacion.models.file_size]),
        ),
    ]
