# Generated by Django 3.1.5 on 2021-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0013_auto_20210115_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='oferta',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
