# Generated by Django 3.1.5 on 2021-01-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0014_auto_20210115_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='oferta',
        ),
    ]
