# Generated by Django 3.1.5 on 2021-01-16 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0015_remove_producto_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='nombre_icono',
            field=models.CharField(default='h', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='aplicacion.categoria'),
        ),
    ]
