# Generated by Django 3.1.5 on 2021-01-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0019_categoria_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategoria',
            name='descripcion',
            field=models.CharField(default='subcategoria', max_length=100),
            preserve_default=False,
        ),
    ]
