# Generated by Django 3.1.5 on 2021-01-20 04:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0020_subcategoria_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategoria',
            name='oferta',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
